#!/usr/bin/env python
"""STDIN에서 STDOUT으로 넘어가는 각각의 줄을 암호화합니다.

평문 텍스트는 문자 데이터이며, 암호 텍스트는 Ascii85로 인코딩된 바이트입니다.

부호화 결과, 암호 텍스트는 평문 텍스트보다 다소 길어지나,
어떤 글자가 부호화되느냐에 따라 정확한 비율은 달라질 수 있습니다.

모든 유니코드 평문 텍스트를 부호화할 수 있지만, ASCII 값이 아닌 입력의 경우,
Ascii85 부호화에 의해 암호 텍스트의 길이가 늘어나기 전에,
먼저 UTF-8로 부호화되기 때문에 부호화의 길이가 더 늘어날 수 있습니다.
"""

from base64 import a85encode, a85decode
import hashlib
import sys


def amateur_encrypt(plaintext: str, key: str) -> bytes:
    encoded_text = plaintext.encode()
    m = hashlib.sha256()
    m.update(key.encode())
    # 전체 평문 텍스트와 일치하도록 키 길이 확장
    hashed_key = m.digest() * (1 + len(encoded_text)//32)
    ciphertext0 = b"".join(
        (a ^ b).to_bytes()
        for a, b in zip(encoded_text, hashed_key))
    ciphertext = b"".join(
        (a ^ b).to_bytes()
        for a, b in zip(reversed(ciphertext0), hashed_key))
    return ciphertext


def amateur_decrypt(ciphertext: bytes, key: str) -> str:
    m = hashlib.sha256()
    m.update(key.encode())
    hashed_key = m.digest() * (1 + len(ciphertext)//32)
    plainbytes0 = b"".join(
        (a ^ b).to_bytes()
        for a, b in zip(ciphertext, hashed_key))
    plainbytes = b"".join(
        (a ^ b).to_bytes()
        for a, b in zip(reversed(plainbytes0), hashed_key))
    return plainbytes.decode()


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(
            "Usage: amateur-crypt [-e|-d] passwd < src > dst",
            file=sys.stderr
        )
    else:
        mode = sys.argv[1]
        key = sys.argv[2]
        if mode == "-e":
            for line in sys.stdin:
                ciphertext = amateur_encrypt(line, key)
                print(a85encode(ciphertext).decode())
        elif mode == "-d":
            # 80개의 '-' 문자로 시작되는 줄은 무시됩니다.
            start = False
            for line in sys.stdin:
                if not start:
                    if line.startswith("-"*80):
                        start = True
                    continue
                line = a85decode(line)
                print(amateur_decrypt(line, key), end="")
        else:
            print(
                "Usage: amateur-crypt [-e|-d] passwd < src > dst",
                file=sys.stderr
            )
