#!/usr/bin/env python
import sys

def print_daily_balance(deposit, interest_rate):
    balance = deposit
    daily_interest = interest_rate/365
    print(" Day | Customer | Internal")
    print("-----+----------+----------")
    for day in range(1, 366):
        print(f" {day:>3d} | {balance:8.2f} | {balance:8.3f}")
        balance = balance * (1 + daily_interest)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(1)
    try:
        deposit = float(sys.argv[1])
        interest_rate = float(sys.argv[2]) / 100
    except ValueError:
        sys.exit(1)

    print_daily_balance(deposit, interest_rate)
