#!/usr/bin/env python
import sys
from decimal import Decimal, ROUND_HALF_EVEN, ROUND_HALF_DOWN

def print_daily_balance(deposit, interest_rate):
    balance = deposit
    daily_interest = interest_rate/365
    print(" Day | Customer | Internal")
    print("-----+----------+----------")
    cents = Decimal('1.00')
    tenths = Decimal('1.000')
    for day in range(1, 366):
        balance = balance.quantize(tenths, rounding=ROUND_HALF_EVEN)
        customer = balance.quantize(cents, rounding=ROUND_HALF_DOWN)
        print(f" {day:>3d} | {customer:8.2f} | {balance:8.3f}")
        balance = balance * (1 + daily_interest)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(1)
    try:
        deposit = Decimal(sys.argv[1])
        interest_rate = Decimal(sys.argv[2]) / 100
    except ValueError:
        sys.exit(1)

    print_daily_balance(deposit, interest_rate)
