#!/usr/bin/env python
import re
from sys import argv, stdin
from collections import Counter

hist = Counter()

if '-w' in argv or '--word' in argv:
    # 단어 히스토그램
    cleaned = re.sub(r'[^\w]', ' ', stdin.read())
    hist = Counter(cleaned.lower().split())
else:
    # 문자 히스토그램
    cleaned = re.sub(r'[^\w]', '', stdin.read())
    hist = Counter(cleaned)

for item, count in hist.most_common():
    print(f"{count}\t{item}")
