#!/usr/bin/env python
from sys import stdin, argv
from collections import deque

window = int(argv[1]) if len(argv) > 1 else 5
nums = deque()

# 초기 숫자 범위로 덱 미리 채우기
for n, num in zip(range(window), stdin):
    nums.append(int(num.rstrip()))

# 초기 합계와 평균 계산
total = sum(nums)
print(total/window)

# 새로운 숫자를 읽을 때마다 이동평균 출력하기
for num in stdin:
    total -= nums.popleft()
    nums.append(int(num.rstrip()))
    total += nums[-1]
    print(total/window)
